{% set name = "fancylog" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fancylog-{{ version }}.tar.gz
  sha256: 404f2d6af461e8e6fa9fabd7eb51867e891422aaf8af78f515de263ff827e26c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - packaging
    - python >=3.6
    - rich

test:
  imports:
    - fancylog
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamltyson/fancylog
  summary: Fancier logging in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamltyson
    - goanpeca
